---
- name: install httpd
  yum: 
   name: httpd
   state: installed
  when: ansible_os_family == 'RedHat'
  notify: start httpd service

- name: install apache2
  apt:
   name: apache2
   state: present
  when: ansible_os_family == 'debian' 
  notify: start httpd service

- name: copy index.html
  copy: 
    src: /home/ansadmin/index.html
    dest: /var/www/html
    mode: 0666 
